export const crops = [
    {
      id: "cannabis",
      name: "Cannabis",
      intervals: [
        {
          name: "Danger Zone (Under Transpiration)",
          color: "#1a6c9c",
          upper: 0.4,
        },
        {
          name: "Early Vegetative Growth / Propagation (Low Transpiration)",
          color: "#22ab9c",
          lower: 0.4,
          upper: 0.8,
        },
        {
          name: "Late Vegetative / Early Flower (Healthy Transpiration)",
          color: "#9cc55b",
          lower: 0.8,
          upper: 1.2,
        },
        {
          name: "Mid / Late Flower (High Transpiration)",
          color: "#e7c12b",
          lower: 1.2,
          upper: 1.6,
        },
        {
          name: "Danger Zone (Over Transpiration)",
          color: "#ce4234",
          lower: 1.6,
        },
      ],
      dew: !0,
      dewColor: "#969696",
      crossColor: "#ffffff",
      axisColor: "#ffffff",
      darkAxis: !1,
    },
    {
      id: "tomatoes",
      name: "Tomatoes",
      intervals: [
        {
          name: "Danger Zone (Under Transpiration)",
          color: "#1a6c9c",
          upper: 0.2,
        },
        {
          name: "Early growth",
          color: "#22ab9c",
          lower: 0.2,
          upper: 0.5,
        },
        {
          name: "Vegetative",
          color: "#9cc55b",
          lower: 0.5,
          upper: 0.8,
        },
        {
          name: "Flowering to mature fruiting",
          color: "#e7c12b",
          lower: 0.8,
          upper: 1.2,
        },
        {
          name: "Danger Zone (Over Transpiration)",
          color: "#ce4234",
          lower: 1.2,
        },
      ],
      dew: !0,
      dewColor: "#969696",
      crossColor: "#ffffff",
      axisColor: "#ffffff",
      darkAxis: !1,
    },
    {
      id: "cannabis-veg1",
      name: "Cannabis - Early Vegetative Growth / Propagation",
      intervals: [
        {
          name: "Early Vegetative Growth / Propagation",
          color: "#22ab9c",
          lower: 0.4,
          upper: 0.8,
        },
      ],
      dew: !1,
      dewColor: "#969696",
      crossColor: "#20303c",
      axisColor: "#20303c",
      darkAxis: !0,
    },
    {
      id: "cannabis-veg2",
      name: "Cannabis - Late Vegetative / Early Flower",
      intervals: [
        {
          name: "Late Vegetative / Early Flower",
          color: "#9cc55b",
          lower: 0.8,
          upper: 1.2,
        },
      ],
      dew: !1,
      dewColor: "#969696",
      crossColor: "#20303c",
      axisColor: "#20303c",
      darkAxis: !0,
    },
    {
      id: "cannabis-veg3",
      name: "Cannabis - Mid / Late Flower",
      intervals: [
        {
          name: "Mid / Late Flower",
          color: "#e7c12b",
          lower: 1.2,
          upper: 1.6,
        },
      ],
      dew: !1,
      dewColor: "#969696",
      crossColor: "#20303c",
      axisColor: "#20303c",
      darkAxis: !0,
    },
    {
      id: "leafy-greens",
      name: "Leafy Greens",
      intervals: [
        {
          name: "Vegetative Growth",
          color: "#9cc55b",
          lower: 0.8,
          upper: 0.95,
          temp_lower: 18,
          temp_upper: 25,
        },
      ],
      dew: !0,
      dewColor: "#969696",
      crossColor: "#20303c",
      axisColor: "#20303c",
      darkAxis: !0,
    },
    {
      id: "cucumber",
      name: "Cucumber",
      intervals: [
        {
          name: "very high humidity – conditions favouring infection of fungal diseases, and reducing photosynthesis",
          color: "#1a6c9c",
          upper: 0.2,
        },
        {
          name: "high humidity – conditions favourable for the survival of fungus pathogens and its development in already infected plants",
          color: "#22ab9c",
          lower: 0.2,
          upper: 0.4,
        },
        {
          name: "optimal humidity for plant cultivation",
          color: "#9cc55b",
          lower: 0.4,
          upper: 1.4,
        },
        {
          name: "insufficient humidity – conditions unfavourable for water use efficiency (efficiency reduction)",
          color: "#e7c12b",
          lower: 1.4,
        },
      ],
      dew: !0,
      dewColor: "#969696",
      crossColor: "#ffffff",
      axisColor: "#ffffff",
      darkAxis: !1,
    },
  ];
  